### PR TITLE
Fix overlapping slots glitch

### LINKED ISSUE #126: Overlapping time slots
It appears this can still happen. The data seems to be correct, as when the app is relaunched it shows the correct times, but during the day itself, the timeline appears to not be updated correctly.

Screenshots:
slack_for_ios_upload_720

slack_for_ios_upload_720-1

### PR DESCRIPTION
**Pull request by willsb**
Closes #126

### CODE REVIEW

File: teferi/ViewModels/TimelineViewModel.swift [hunk 1]
```diff
@@ -78,4 +96,11 @@ class TimelineViewModel
             self.timeSlotUpdatingVariable.value = index
         }
     }
+    
+    private func filterRefreshStates(_ appState: AppState) -> Bool { return appState == .active }
+    
+    private func mapIntoVoid(_ appState: AppState) -> Void
```
Comment (amulware) [inline teferi/ViewModels/TimelineViewModel.swift]: This method has a name that does not really describe what it is doing.

File: teferi/ViewModels/TimelineViewModel.swift [hunk 2]
```diff
@@ -78,4 +96,11 @@ class TimelineViewModel
             self.timeSlotUpdatingVariable.value = index
         }
     }
+    
+    private func filterRefreshStates(_ appState: AppState) -> Bool { return appState == .active }
```
Comment (amulware) [inline teferi/ViewModels/TimelineViewModel.swift]: Why not just use a closure instead of this method?

File: teferi/ViewModels/TimelineViewModel.swift [hunk 3]
```diff
@@ -17,7 +19,17 @@ class TimelineViewModel
     let isEditingObservable : Observable<Bool>
     let timeSlotUpdatingObservable : Observable<Int>
     let timeSlotCreationObservable : Observable<Int>
-    
+    private(set) lazy var refreshScreenObservable : Observable<Void> =
```
Comment (amulware) [inline teferi/ViewModels/TimelineViewModel.swift]: Why isn't this initialised in the constructor like the other observables?

Comment (willsb) [inline teferi/ViewModels/TimelineViewModel.swift]: One can't reference `self.` before `init`ing every constant field, but this one requires a reference to `self.`, hence needs to be lazy
