### PR TITLE
Fix start time editing

### LINKED ISSUE #908: Bug when editing the start time of grouped slots.
The detail views are based on the start time to get the first slot for the grouped timeSlots (same for the single slot). when we edit the start time it is still trying to find the slot with the old time and it fails. In this situation it was suppose to dismiss the detail view. It was not dismissing back enough and thus ending in strange state with wrong data in the UI and a bit non responsive or in a crash (crash when editing the start time of the first grouped slot and trying to open that slot for a second time)

### PR DESCRIPTION
**Pull request by sofokli1**
Closes #908 

This approach propagates the start time from the VC that the change happens down to the details view for grouped and single slot.

An other approach for this kind of issues would be to have identifiers per timeSlot. It seemed too big of a change for this PR but something worth thinking about.

### CODE REVIEW

File: teferi/Extensions/ArrayExtensions.swift [hunk 1]
```diff
@@ -109,6 +109,35 @@ extension Array where Element : Hashable
     }
 }
 
+extension Array where Element == TimeSlot
```
Comment (Odrakir) [inline teferi/Extensions/ArrayExtensions.swift]: This extension is too specific to be part of Array Extensions (at least of this file). The same happens with the next one, but let's leave it like this for now.

File: teferi/UI/Modules/Timeline/TimeSlotDetail/TimeslotDetailViewModel.swift [hunk 2]
```diff
@@ -7,40 +7,70 @@ class TimeslotDetailViewModel
...
         self.metricsService = metricsService
         self.smartGuessService = smartGuessService
         self.timeService = timeService
         self.categoryProvider = DefaultCategoryProvider(timeSlotService: timeSlotService)
         
-        timelineItemsObservable
-            .map(filterSelectedElement(for: startDate))
+        updateStartDateSubject.asObservable().subscribe(onNext: { [unowned self] (date) in
+            self.startDate = date
+            print(self.startDate, #function)
```
Comment (Odrakir) [inline teferi/UI/Modules/Timeline/TimeSlotDetail/TimeslotDetailViewModel.swift]: print

File: teferi/UI/Modules/Timeline/TimeSlotDetail/TimeslotDetailViewModel.swift [hunk 3]
```diff
@@ -78,41 +128,40 @@ class TimeslotDetailViewModel
...
+            return TimelineItem(withTimeSlots: [timeSlotToShow],
+                                category: timeSlotToShow.category,
+                                duration: timeSlotToShow.duration != nil ?
+                                    timeSlotToShow.duration! :
+                                    self.timeService.now.timeIntervalSince(timeSlotToShow.startTime),
+                                isRunning: isRunning)
+        }
+        else
+        {
+            print(startDate, #function)
```
Comment (Odrakir) [inline teferi/UI/Modules/Timeline/TimeSlotDetail/TimeslotDetailViewModel.swift]: print
