### PR TITLE
Fix faulty fading duration line behaviours

### LINKED ISSUE #171: Investigate wrong time slot having faded line
screen shot 2016-12-05 at 10 07 34

I guess this might happen if a time slot that was the last in a previous day is reused for a different part of the list, and that the line fade is not disabled in that case.

### LINKED ISSUE #172: Some time slots do not show their line
screen shot 2016-12-05 at 10 07 34

### PR DESCRIPTION
**Pull request by amulware**
Closes #171
Closes #172

### CODE REVIEW

File: teferi/Views/TimelineCell.swift [hunk 1]
```diff
@@ -145,6 +123,25 @@ class TimelineCell : UITableViewCell
...
+        guard self.lineFadeView == nil else { return }
+        
+        let bottomFadeStartColor = Color.white.withAlphaComponent(1.0)
+        let bottomFadeEndColor = Color.white.withAlphaComponent(0.0)
+        let bottomFadeOverlay = self.fadeOverlay(startColor: bottomFadeStartColor, endColor: bottomFadeEndColor)
+        let fadeView = AutoResizingLayerView(layer: bottomFadeOverlay)
+        self.lineView.addSubview(fadeView)
+        fadeView.snp.makeConstraints { make in
+            make.bottom.equalToSuperview()
+            make.left.equalToSuperview()
```
Comment (willsb) [inline teferi/Views/TimelineCell.swift]: `make.bottom.left.right.equalToSuperview()`

File: teferi/Views/TimelineCell.swift [hunk 2]
```diff
@@ -145,6 +123,25 @@ class TimelineCell : UITableViewCell
         self.indicatorDot.layoutIfNeeded()
     }
     
+    private func ensureLineFadeExists()
+    {
+        guard self.lineFadeView == nil else { return }
+        
+        let bottomFadeStartColor = Color.white.withAlphaComponent(1.0)
```
Comment (willsb) [inline teferi/Views/TimelineCell.swift]: Any reason why this is created manually and not via the IB instead?

Comment (amulware) [inline teferi/Views/TimelineCell.swift]: This way it will be created for far fewer slots. Since we have to setup the layer manually anyways (as far as I'm aware), this seems alright to me.
