### PR TITLE
Fix not scrolling to bottom for voting

### LINKED ISSUE #738: Timeline vote notification doesn't direct user to the right place
Timeline vote notifications work like a charm but just open the correct timeline, though these should scroll to the 'vote' section, so user can give thumbs up/down right away. At the moment these are just opening the timeline at the top.

### PR DESCRIPTION
**Pull request by sofokli1**
closes #738

### CODE REVIEW

File: teferi/AppDelegate.swift [hunk 1]
```diff
@@ -132,8 +132,6 @@ class AppDelegate : UIResponder, UIApplicationDelegate
             }
         }
         
-        appLifecycleService.publish(isInBackground ? .movedToBackground : .movedToForeground(withDailyVotingNotificationDate: dailyVotingNotificationDate))
```
Comment (Odrakir) [inline teferi/AppDelegate.swift]: Why is this not needed anymore?

File: teferi/Services/Implementations/State/DefaultAppLifecycleService.swift [hunk 2]
```diff
@@ -3,7 +3,7 @@ import RxSwift
 class DefaultAppLifecycleService : AppLifecycleService
 {
     let lifecycleEventObservable : Observable<LifecycleEvent>
-    private let lifecycleSubject = PublishSubject<LifecycleEvent>()
+    private let lifecycleSubject = BehaviorSubject<LifecycleEvent>(value: LifecycleEvent.movedToForeground(withDailyVotingNotificationDate: nil))
```
Comment (Odrakir) [inline teferi/Services/Implementations/State/DefaultAppLifecycleService.swift]: How about it being a `BehaviorSubject<LifecycleEvent?>` with a nil initial value and filtering out nil in the `lifecycleEventObservable`? Otherwise the first event will be moved to foreground without notification date.

File: teferi/UI/Modules/Timeline/TimelineViewController.swift [hunk 3]
```diff
@@ -57,6 +57,10 @@ class TimelineViewController : UIViewController
     {
         super.viewDidLoad()
         
+        viewModel.dailyVotingNotificationObservable
```
Comment (Odrakir) [inline teferi/UI/Modules/Timeline/TimelineViewController.swift]: Can you move this down to where the other viewModel bindings are? Maybe it's even worth it to create a `bindViewModel` method for all of them, your call.

File: teferi/UI/Modules/Timeline/TimelineViewController.swift [hunk 4]
```diff
@@ -125,21 +129,19 @@ class TimelineViewController : UIViewController
             self.delegate?.didScroll(oldOffset: old + topInset, newOffset: new + topInset)
         })
         .addDisposableTo(disposeBag)
+        
+        viewModel.didBecomeActiveObservable
```
Comment (Odrakir) [inline teferi/UI/Modules/Timeline/TimelineViewController.swift]: Won't this show the voting UI everytime the app comes from background on that day, regardless if you voted before or not?

File: teferi/AppDelegate.swift (hunk 1 above)
Comment (sofokli1) [reply teferi/AppDelegate.swift]: my bad, i thought it was the same as the one in `applicationDidBecomeActive`
