### PR TITLE
Fixes Black Screen glitch

### LINKED ISSUE #88: Find and resolve black-screen issue
When leaving the app running over night, and sometimes when opening it from a notification, it shows up only as a black screen and needs to be restarted.

### PR DESCRIPTION
**Pull request by willsb**
Closes #88

### CODE REVIEW

File: teferi/AppDelegate.swift [hunk 1]
```diff
@@ -62,6 +62,15 @@ class AppDelegate : UIResponder, UIApplicationDelegate
         //Start metrics
         self.metricsService.initialize()
```
Comment (amulware) [inline teferi/AppDelegate.swift]: I believe this line should also be in `initializeInterfaceIfNeeded()`.
