### PR TITLE
Log finished goals

### LINKED ISSUE #921: Track of how many users achieve or fail the goal
We want to know of how many users who set a goal, manage to achieve or fail it.

### PR DESCRIPTION
**Pull request by sofokli1**
closes #921

### CODE REVIEW

File: teferi/AppDelegate.swift [hunk 1]
```diff
@@ -201,6 +203,32 @@ class AppDelegate : UIResponder, UIApplicationDelegate
         
         return notification.date
     }
+    
+    private func logFinishedGoals()
```
Comment (Odrakir) [inline teferi/AppDelegate.swift]: Please, move this out the app delegate and inside `DefaultGoalService`(injecting the appropiate services)
