### PR TITLE
Fix for permission overlay

### LINKED ISSUE #91: Constrain location-permission overlay to main view
It currently appears to have a fixed size and is only partly visible on smaller screens.

### PR DESCRIPTION
**Pull request by willsb**
Closes #91

### CODE REVIEW

File: teferi/ViewControllers/MainViewController.swift [hunk 1]
```diff
@@ -199,9 +199,9 @@ class MainViewController : UIViewController
                 guard permissionView == nil else { return }
                 
                 let isFirstTimeUser = !self.settingsService.canIgnoreLocationPermission
-                self.permissionView =
-                    (Bundle.main.loadNibNamed("PermissionView", owner: self, options: nil)!.first
-                        as! PermissionView!).inject(self.settingsService, isFirstTimeUser: isFirstTimeUser)
+                let view = Bundle.main.loadNibNamed("PermissionView", owner: self, options: nil)!.first as! PermissionView!
```
Comment (amulware) [inline teferi/ViewControllers/MainViewController.swift]: +1 For great naming. :D
